Algoritmo "aula12-atv-somaparmentro-referencia-procendimento"
Var
   X : inteiro
   Y : inteiro
   Procedimento soma (var A, B: inteiro)
   inicio
         A <- A + 1
         B <- B + 2
         escreval (" Recibi o valor ", A)
         escreval ("Recebi o valor ", B)
         escreval ("A soma entre os dois é ", A + B)
   FIMPROCEDIMENTO


Inicio
      x <- 5
      y <- 3
      soma (x, y))
      escreval (" O valor de x = ", x)
      escreval (" O valor de y = ", y)


Fimalgoritmo