Algoritmo "Aula3-comando-de-entrada-e-operadores-ativ4
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : funçoes aritimeticas
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/07/2022
Var
angulo, s:real


Inicio
escreva ("informe um angulo: " )
leia (angulo)
s<-sen (grauprad (angulo))

escreva (" o seno de ", angulo, " é igual a ", s)



Fimalgoritmo