Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : João Marcos
// Data atual  : 20/07/2022
Var
N1, N2: inteiro
M: Real

Inicio
escreva ("Digite um número ")
leia (N1)
escreva("Digite outro número ")
leia (N2)
M<- (N1+N2)/2
escreva("a média entre ", N1, " e ", N2, " é igual a ", M)


Fimalgoritmo