Algoritmo "Aula13-funcao-fatorial"
var
numero :inteiro
fatorial : inteiro
funcao fatorial1 ( valor: inteiro): inteiro
var
contador: inteiro
resultado: inteiro
inicio
resultado <-1
para contador <- 1 ate valor faca
resultado <- resultado * contador
fimpara
retorne resultado
fimfuncao



Inicio
   escreval (" Digite um número")
   leia (numero)
   fatorial <- fatorial1 (numero),
   escreval (" O fatorial de ", numero, " é igual a", fatorial)


Fimalgoritmo