Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : João Marcos
// Data atual  : 20/07/2022
Var
N1, N2, S: inteiro


Inicio
escreva ("Digite um número ")
leia (N1)
escreva("Digite outro número ")
leia (N2)
s <- N1+N2
escreva("a soma entre ", N1, " e ", N2, " é igual a ", s)


Fimalgoritmo