Algoritmo "primeiro algoritimo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : primeiro
// Autor(a)    : João Marcos
// Data atual  : 18/07/2022
Var
//
msg:caractere


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
msg<-("olá mundo!")
   escreval("mensagem ",msg)
   escreva("Me Livrei da maldição")


Fimalgoritmo